name: Release the up-to-date container on dockerhub following cli releases.
# Every morning around 8:00 GMT

on:
  workflow_dispatch:
#  schedule:
#    #Monday through Friday around 7:00 UTC (not using exact hours helps with runners availability)
#    - cron: '58 6 * * 1,2,3,4,5'

env:
  executable-name: 'scalingo'
  executable-archive-name-pattern: 'scalingo_RELEASE_TAG_VERSION_linux_386'
  executable-archive-extention: 'tar.gz'
  target-repository: 'scalingo/cli'
  target-dockerhub-registry: 'rcambonie/scalingo-cli'

jobs:
  get-release-version:
    runs-on: ubuntu-latest
    outputs:
      release-tag-version: ${{ steps.latest-release-info.outputs.tag-version }}
    steps:
      - name: Get target release version
        id: latest-release-info
        run: |
          RELEASE_TAG_VERSION=$(curl --silent "https://api.github.com/repos/${{ env.target-repository }}/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
          echo "::set-output name=tag-version::$RELEASE_TAG_VERSION"

  dynamic-variables:
    needs:
      - get-release-version
    outputs:
      executable-name: ${{ steps.executable-name.outputs.value }}
      executable-archive-name: ${{ steps.executable-archive-name.outputs.value }}
      executable-archive-extention: ${{ steps.executable-archive-extention.outputs.value }}
      target-repository: ${{ steps.target-repository.outputs.value }}
    runs-on: ubuntu-latest
    steps:
      - name: Executable archive name with replaced release version tag
        id: executable-archive-name
        #'Simple' variable remplacement. We use the bash replace syntax as it is the default shell on github runners
        run: |
          EXECUTABLE_ARCHIVE_NAME=${{ env.executable-archive-name-pattern }}
          RELEASE_TAG_VERSION=${{ needs.get-release-version.outputs.release-tag-version }}
          EXECUTABLE_ARCHIVE_NAME=${EXECUTABLE_ARCHIVE_NAME//RELEASE_TAG_VERSION/"$RELEASE_TAG_VERSION"}     
          echo "::set-output name=value::$EXECUTABLE_ARCHIVE_NAME"

      - name: Executable name from environment variable
        id: executable-name
        run: |
          EXECUTABLE_NAME=${{ env.executable-name }}
          echo "::set-output name=value::$EXECUTABLE_NAME"

      - name: Executable archive file extention from environment variable
        id: executable-archive-extention
        run: |
          EXECUTABLE_ARCHIVE_EXTENTION=${{ env.executable-archive-extention }}
          echo "::set-output name=value::$EXECUTABLE_ARCHIVE_EXTENTION"

      - name: Target repository from environment variable
        id: target-repository
        run: |
          TARGET_REPOSITORY=${{ env.target-repository }}
          echo "::set-output name=value::$TARGET_REPOSITORY"

  dockerfile-from-template:
    needs:
      - get-release-version
      - dynamic-variables
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve the repository files
        uses: actions/checkout@v3

      - name: Generate the target dockerfile by replacing the variables in Dockerfile_template template
        run: |
          sed -i 's|RELEASE_TAG_VERSION|${{ needs.get-release-version.outputs.release-tag-version }}|g' Dockerfile
          sed -i 's|TARGET_REPOSITORY|${{ needs.dynamic-variables.outputs.target-repository }}|g' Dockerfile
          sed -i 's|EXECUTABLE_ARCHIVE_NAME_PATTERN|${{ needs.dynamic-variables.outputs.executable-archive-name }}|g' Dockerfile
          sed -i 's|EXECUTABLE_ARCHIVE_EXTENTION|${{ needs.dynamic-variables.outputs.executable-archive-extention }}|g' Dockerfile
          sed -i 's|EXECUTABLE_NAME|${{ needs.dynamic-variables.outputs.executable-name }}|g' Dockerfile

      - name: Upload resulting Dockerfile as artifact for reference
        uses: actions/upload-artifact@v3
        with:
          name: generated-dockerfile
          path: ./Dockerfile

  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest
    needs:
      - get-release-version
      - dockerfile-from-template
    steps:
      - name: Retrieve Dockerfile
        uses: actions/download-artifact@v3
        with:
          name: generated-dockerfile
          path: .

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: |
            ${{ env.target-dockerhub-registry }}:latest 
            ${{ env.target-dockerhub-registry }}:${{ needs.get-release-version.outputs.release-tag-version }}
          # build on feature branches, push only on master branch
          push: ${{ github.ref == 'refs/heads/master' }}
